[package]
name = "chip8"
version = "0.1.0"
authors = ["Fernando Martins <martins.fernandomiguel@gmail.com>"]

[dependencies]
rustc-serialize = "0.3" 
docopt = "0.6"
sdl2 = "0.15"
num = "0.1"
rand = "0.3"
enum_primitive = "*"
